version: '3.9'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
